name: "Manual Release workflow"

on:
  workflow_dispatch:
    inputs:
      version:
        description: Release version
        required: true

jobs:
  tagged-release:
    runs-on: ubuntu-18.04
    strategy:
      matrix:
        java-version: [ 8 ]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: rohit/manual-release-flow-test
      - uses: actions/setup-java@v2
        with:
          distribution: 'temurin'
          java-version: ${{ matrix.java-version }}
          cache: 'maven'
      - name: Configure Git user
        run: |
          git config user.email "actions@github.com"
          git config user.name "GitHub Actions"
      - name: Set version in env
        run: |
          version="${GITHUB_REF#refs/tags/}"
          echo "RELEASE_VERSION=${{ github.event.inputs.version }}" >> $GITHUB_ENV
      - name: Generate changelog
        id: changelog
        uses: metcalfc/changelog-generator@v0.4.4
        with:
          myToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Build and deploy
        run: |
          pwd
          gpg --generate-key
          gpg --list-keys
          git checkout -b release/${RELEASE_VERSION}
          mvn -B -X release:prepare -P release -DreleaseVersion=${RELEASE_VERSION} -Dmaven.wagon.httpconnectionManager.ttlSeconds=60 -Darguments="-DskipTests=true -Dmaven.test.skip=true -P skip-unit-tests -P skip-integration-tests -X"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Create pull request
        uses: repo-sync/pull-request@v2
        with:
          source_branch: "release/${{ github.event.inputs.version }}"
          github_token: ${{ secrets.GITHUB_TOKEN }}
      - name: Copy Artifacts
        uses: ncipollo/release-action@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: /home/runner/work/blueflood/blueflood/blueflood-all/target/blueflood-all-${{ github.event.inputs.version }}-jar-with-dependencies.jar
          tag: "blueflood-${{ github.event.inputs.version }}"
