# Run unit tests on each master merge for display in a README badge and on each PR as a requirement for merging.
name: Unit tests
on:
  push:
    branches: [rohit/debug-failed-ITs]
jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '8'
          cache: 'maven'
      - run: |
          mvn clean install -P skip-unit-tests,skip-integration-tests
          cd blueflood-integration-tests
          mvn clean install
